targets:
  $default:
    builders:
      graphql_codegen:
        options:
          clients:
            - graphql
          addTypename: false
          scalars:
            DateTimeISO: 
              type: DateTime
