name: flutter_graphql_sample
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  graphql_flutter: ^5.1.2
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  flutter_bloc: 8.1.6
  get_it: ^8.0.3
  go_router: ^16.0.0
  bloc_concurrency: ^0.2.5
  gql: ^1.0.1-alpha+1730759315362
  graphql: ^5.2.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  graphql_codegen: ^1.2.4
  test: ^1.25.15

flutter:
  uses-material-design: true

  assets:
    - .env
